title: 'Interactive Prolog Book Example'
author: >
  <a href="mailto:K.Sokol@bristol.ac.uk">Kacper Sokol</a>,
  University of Bristol, United Kingdom
copyright: '2021'
logo: src/img/owl.svg

exclude_patterns:
  - .DS_Store
  - __pycache__
  - .github
  - README.md
  - src/ex
  - src/code/temp

execute:
  execute_notebooks: off

html:
  favicon: src/img/owl.svg
  use_edit_page_button: true
  use_repository_button: true
  use_issues_button: true
  extra_footer: >
    This book is a template for building interactive Prolog books using
    SWI Prolog and SWISH.
    The book is based on
    <a href="https://jupyterbook.org/intro.html">Jupyter Book</a>, and
    the Prolog support is enabled with our custom
    <a href="https://github.com/simply-logical/sphinx-prolog">sphinx-prolog</a>
    extension.
    The source of this book is available on
    <a href="https://github.com/simply-logical/prolog-book-template">GitHub</a>.
  extra_navbar: ''
  google_analytics_id: '261828628'
  home_page_in_navbar: true

parse:
  myst_enable_extensions:
    - colon_fence
    - substitution

repository:
  url: https://github.com/simply-logical/prolog-book-template

sphinx:
  extra_extensions:
    - sphinx_prolog.infobox
    - sphinx_prolog.pprolog
    - sphinx_prolog.solex
    - sphinx_prolog.swish
  config:
    html_extra_path:
      - README.md
      - LICENCE
      - CNAME
      - .nojekyll
    numfig_format:
      figure: 'Figure %s'
    numfig_secnum_depth: 2
    # Configure Sphinx-copybutton
    # <https://sphinx-copybutton.readthedocs.io/en/latest/>
    copybutton_prompt_text: ''
    copybutton_only_copy_prompt_lines: false
    copybutton_remove_prompts: false
    # NOTE: if a copybutton is added to a SWISH code box, inheritance breaks!
    # <https://github.com/executablebooks/sphinx-copybutton/issues/115>
    # To avoid this we need to use a custom CSS selector
    copybutton_selector: 'div.highlight:not(.extract):not(.swish) > pre'
    # Configure sphinx-prolog <https://github.com/simply-logical/sphinx-prolog>
    sp_exercise_directory: src/ex/
    sp_code_directory: src/code/
    sp_swish_url: https://swish.simply-logical.space/
    sp_swish_book_url: https://book-template.simply-logical.space/
    sp_swish_hide_examples: false
